version: "2"

services:
  linux:
    image: maav-mission9
    privileged: true
    volumes:
      - .:/mission9-2021:rw  # Copy code into Docker container
      # GUI Settings for Linux only...?
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1yy
    network_mode: "host"
    container_name: maav-mission9
    command: "/bin/bash --init-file scripts/source-ros.sh"

  wsl:
    image: maav-mission9
    privileged: true
    volumes:
      - .:/mission9-2021:rw  # Copy code into Docker container
      # TODO Fix GUI settings for Windows
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY
    network_mode: "host"
    container_name: maav-mission9
    command: "/bin/bash --init-file scripts/source-ros.sh"


  mac:
    image: maav-mission9
    privileged: true
    volumes:
      - .:/mission9-2021:rw # Copy code into Docker container
    environment:
      - DISPLAY
    network_mode: "host"
    container_name: maav-mission9
    command: "/bin/bash --init-file scripts/source-ros.sh"
